# Generated by Django 3.2.5 on 2022-05-25 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowershopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowershopapp.district')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowershopapp.place')),
            ],
        ),
    ]
