# Generated by Django 3.2.5 on 2022-05-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershopapp', '0002_flower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='place',
        ),
        migrations.AddField(
            model_name='flower',
            name='place',
            field=models.ManyToManyField(to='flowershopapp.Place'),
        ),
    ]
