# Generated by Django 3.2.5 on 2022-05-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowershopapp', '0005_alter_flower_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='district',
        ),
    ]
