# Generated by Django 3.2.5 on 2022-05-25 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowershopapp', '0006_remove_flower_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=250)),
                ('customer_phone', models.CharField(max_length=12)),
                ('customer_email', models.CharField(max_length=255)),
                ('customer_address', models.TextField()),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowershopapp.district')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowershopapp.flower')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowershopapp.place')),
            ],
        ),
    ]
